Repository pagopa/pagopa-azure-devops, pull requests merged in 2023-01, with the labels that each got.

#113 PAGOPA-600 subkey generation
  azure-devops/gps/.terraform.lock.hcl
  azure-devops/gps/00_secrets_gps.tf
  azure-devops/gps/06_pagopa-gpd-payments.tf
Labels: status: applied

#115 PAGOPA-600 split payments subscription keys
  azure-devops/gps/00_secrets_gps.tf
  azure-devops/gps/06_pagopa-gpd-payments.tf
Labels: enhancement, status: applied

#118 feat : DB migration
  azure-devops/iac/04_iac_nodo.tf
Labels: status: applied

#123 fix branch for nodo
  azure-devops/iac/04_iac_nodo.tf
  azure-devops/iac/README.md
Labels: status: applied

#125 add-dev_container_registry_service_conn-deploy_nodo
  azure-devops/nodo/06_pagopa-nodo-service.tf
Labels: status: applied

#120 feat: PAGOPA-209 Add var to pipeline [API-CFG]
  azure-devops/app/00_secrets_dev.tf
  azure-devops/app/00_secrets_prod.tf
  azure-devops/app/00_secrets_uat.tf
  azure-devops/app/06_pagopa-api-config-fe.tf
  azure-devops/app/README.md
Labels: status: applied

#128 uncomment-image_repository_name
  azure-devops/nodo/06_pagopa-nodo-service.tf
Labels: status: applied

#130 fix: Nodo sonar cfg
  azure-devops/nodo/06_pagopa-nodo-service.tf
  azure-devops/nodo/README.md
Labels: status: applied

#134 feat: Wfesp deploy pipeline
  azure-devops/nodo/06_pagopa-wfesp-service.tf
  azure-devops/nodo/README.md
Labels: status: applied

#142 feat: PAGOPA-615 add pipelines for micronaut poc
  azure-devops/shared/00_secrets_shared.tf
  azure-devops/shared/06_pagopa-poc-micronaut-service.tf
  azure-devops/shared/README.md
Labels: enhancement
