Repository pagopa/pagopa-azure-devops, pull requests merged in 2023-09, with the labels that each got.

#246 chore: fix and refactoring GPS domain TLS
  azure-devops/app/00_secrets_dev.tf
  azure-devops/app/00_secrets_prod.tf
  azure-devops/app/00_secrets_uat.tf
  azure-devops/app/03_service_connections_tls_certificate.tf
  azure-devops/app/06_pagopa-api-config-fe.tf
  azure-devops/app/README.md
  azure-devops/gps/.terraform.lock.hcl
  azure-devops/gps/00_key_vault.tf
  azure-devops/gps/03_service_connections_tls_certificate.tf
  azure-devops/gps/05_tlscert-weudev-gps-internal-dev-platform-pagopa-it.tf
  azure-devops/gps/05_tlscert-weuprod-gps-internal-prod-platform-pagopa-it.tf
  azure-devops/gps/05_tlscert-weuuat-gps-internal-uat-platform-pagopa-it.tf
  azure-devops/gps/README.md
Labels: status: applied

#231 feat: adding pipelines for QI namespace PQI-27
  azure-devops/.env/qi_state.tfvars
  azure-devops/qi/.terraform.lock.hcl
  azure-devops/qi/00_key_vault.tf
  azure-devops/qi/00_secrets_prod.tf
  azure-devops/qi/00_secrets_qi.tf
  azure-devops/qi/01_project.tf
  azure-devops/qi/03_service_connections_aks.tf
  azure-devops/qi/03_service_connections_tls_certificate.tf
  azure-devops/qi/05_tlscert-weudev-qi-internal-dev-platform-pagopa-it.tf
  azure-devops/qi/05_tlscert-weuuat-qi-internal-uat-platform-pagopa-it.tf
  azure-devops/qi/99_main.tf
  azure-devops/qi/99_variables.tf
Labels: enhancement

#252 [PRDP-130] feat: Added receipt-pdf-generator pipeline config
  azure-devops/receipts/00_secrets_receipts.tf
  azure-devops/receipts/06_pagopa-receipts-generator.tf
  azure-devops/receipts/06_pagopa-receipts-service.tf
Labels: enhancement

#259 [PRDP-136] Added blob storage conn string to datastore secrets
  azure-devops/receipts/06_pagopa-receipts-data-store.tf
Labels: enhancement

#256 fix: resolved typo on `image_repository_name`
  azure-devops/nodo/06_pagopa-nodo-re-to-datastore.tf
Labels: bug

#257 [PAGOPA-1176] chore: Remove gpd-reporting-batch deploy
  azure-devops/gps/.terraform.lock.hcl
  azure-devops/gps/06_pagopa-gpd-reporting-batch.tf
  azure-devops/gps/README.md
Labels: status: applied
