Repository pagopa/pagopa-azure-devops, pull requests merged in 2023-04, with the labels that each got.

#180 feat: Pagopa-wallet-first-configuration
  azure-devops/.env/wallet_state.tfvars
  azure-devops/iac/00_secrets_kv_wallet.tf
  azure-devops/iac/04_iac_wallet.tf
  azure-devops/iac/99_variables.tf
  azure-devops/iac/README.md
  azure-devops/wallet/.terraform.lock.hcl
  azure-devops/wallet/00_key_vault.tf
  azure-devops/wallet/00_secrets_prod.tf
  azure-devops/wallet/00_secrets_wallet.tf
  azure-devops/wallet/01_project.tf
  azure-devops/wallet/03_service_connections_aks.tf
  azure-devops/wallet/03_service_connections_tls_certificate.tf
  azure-devops/wallet/05_tlscert-weudev-wallet-internal-dev-platform-pagopa-it.tf
  azure-devops/wallet/05_tlscert-weuuat-wallet-internal-uat-platform-pagopa-it.tf
  azure-devops/wallet/06_pagopa-wallet-service.tf
  azure-devops/wallet/99_main.tf
  azure-devops/wallet/99_variables.tf
  azure-devops/wallet/README.md
Labels: status: applied

#188 feat: Add reporting fn devops pipelines [PAGOPA-698]
  azure-devops/gps/06_pagopa-gpd-reporting-analysis.tf
  azure-devops/gps/06_pagopa-gpd-reporting-service.tf
  azure-devops/gps/README.md
Labels: enhancement

#187 feat: Add pipeline for pagoPA-platform-authorizer
  azure-devops/shared/00_secrets_shared.tf
  azure-devops/shared/06_pagopa-platform-authorizer-service.tf
  azure-devops/shared/README.md
Labels: enhancement, apply in progress, DEV
